--- #YAML:1.0
name:               Text-Corpus-NewYorkTimes
version:            1.01
abstract:           Interface to New York Times corpus.
author:
    - Jeff Kubina (jeff.kubina@gmail.com)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:           1.15
    Date::Manip:          5.54
    Log::Log4perl:        1.24
    Path::Class:          0.16
    XML::LibXML:          1.69
    XML::LibXML::XPathContext:  1.69
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
